# --- Chain ---
rpc_url: "https://mawari-testnet.rpc.caldera.xyz/http"
chain_id: 576

# --- Contracts ---
nft_contract: "0x158752a787bBac275d0096b6292D7e2da411876D"
delegation_hub: "0x5721fc62C7348790bcF58d3a3165a3bbbfCBc1BA"

# --- Docker image ---
docker_image: "us-east4-docker.pkg.dev/mawarinetwork-dev/mwr-net-d-car-uses4-public-docker-registry-e62e/mawari-node:latest"

# --- Wallets ---
owner_private_key: ""     # PK untuk approve + delegate + fund burner
owner_address: ""         # opsional; kalau kosong di-derive dari PK

# --- Auto discover tokenIds dari mint manual ---
auto_discover_token_ids: true
discovery:
  window_blocks: 50000     # scan 50k blok terakhir; ubah kalau perlu
  include_mints_only: false  # kalau true, hanya ambil Transfer dari address 0x0

# --- (opsional) tokenIds statik; diabaikan kalau auto_discover true dan ada hasil ---
token_ids: []

# --- Funding burner dari owner ---
min_burner_balance: "0.5"     # kalau saldo burner < nilai ini → kirim
fund_burner_amount: "1"       # jumlah native MAWARI dari owner ke burner
